---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Repositories:
  - Real World Developers:
      - icon: si-github-#FFFFFF
        href: https://github.com/realworlddevelopers
  - Christian Lempa:
    - icon: si-github-#FFFFFF
      href: https://github.com/christianlempa

- Cloud Services:
  - Cloudflare:
    - icon: cloudflare.png
      href: https://dash.cloudflare.com
  - Namecheap:
    - abbr: N
      href: https://www.namecheap.com/myaccount/login/?ReturnUrl=%2f

- Cloud Platforms:
  - Microsoft Azure:
    - icon: azure.svg
      href: https://portal.azure.com
  - Amazon Web Service:
    - icon: aws.png
      href: https://aws.amazon.com/console/

