---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

title: RWD Homelab
favicon: /icons/favicon.ico
headerStyle: clean
# theme: dark 
color: slate

# background: 
#   image: https://images.unsplash.com/photo-1637825891028-564f672aa42c
#   blur: xl # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
#   brightness: 90 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
#   opacity: 60 # 0-100

cardBlur: sm

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

# useEqualHeights: true
# disableCollapse: true
# showStats: true
# statusStyle: "dot"

layout:
  Network:
    header: true
    style: row
    columns: 4
  Cloud Platforms:
    header: true
    style: row
    columns: 4
  Cloud Services:
    header: true
    style: row
    columns: 4
  Local Services:
    header: true
    style: row
    columns: 4
  Security and Identity:
    icon: mdi-shield-lock-#FFFFFF
    header: true
    style: row
    columns: 4
  Repositories:
    header: true
    style: row
    columns: 4


