---
# For configuration options and examples, please see:
# https://gethomepage.dev/widgets/#info-widgets

- logo:
    icon: /images/RWDevs-NuGet.png # optional
    
- resources:
    cpu: true
    memory: true
    disk: /
    label: Docker Server

- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    format:
        timeStyle: short
        hour12: true
