services:
  reverse-proxy:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      # logging config (levels are TRACE, DEBUG, INFO, WARN, ERROR, FATAL, and PANIC)
      - --log.level=INFO
      #- --log.filepath=/var/log/traefik.log
      #- --accesslog=true
      #- --accesslog.filepath=/var/log/traefik-access.log
      # enable traefik dashboard
      - --api.dashboard=true
      - --api.insecure=true
      # allow traefik to discover docker containers
      - --providers.docker=true
      - --providers.docker.network=proxy
      - --providers.docker.exposedbydefault=false
      # setup insecure listener that redirects all traffice to TLS
      - --entryPoints.web.address=:80
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.websecure.address=:443
      # setup TLS config for websecure listener
      - --entrypoints.websecure.asDefault=true
      #- --entrypoints.websecure.tls=true
      - --entryPoints.websecure.http.tls.certResolver=cloudflare
      - --entryPoints.websecure.http.tls.domains[0].main=local.rwdevs.com
      - --entryPoints.websecure.http.tls.domains[0].sans=*.local.rwdevs.com
      - --serversTransport.insecureSkipVerify=true
      # setup LetsEncrypt
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.0.0.1:53
      #- --certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.cloudflare.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.cloudflare.acme.email=****
      - --certificatesresolvers.cloudflare.acme.storage=acme.json
      
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - proxy
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN} 
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS}
    env_file: traefik.env 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - CHANGE_TO_COMPOSE_DATA_PATH/traefik/acme.json:/acme.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`proxy.local.rwdevs.com`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=traefik-auth
      - traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}
networks:
  proxy:
    name: proxy
    external: true
