version: '3.1'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: mysql_database_name
      MYSQL_USER: mysql_user_name
      MYSQL_PASSWORD: mysql_user_password
    ports:
      - 3306:3306
    volumes:
      - docker_compose_folder/mysql_data:/var/lib/mysql
volumes:
  mysql_data:
