---
networks:
  proxy:
    external: true
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_DEBUG=true
        - WATCHTOWER_INCLUDE_STOPPED=true
        - WATCHTOWER_REVIVE_STOPPED=true
        - WATCHTOWER_SCHEDULE=0 0 0 * * *
        # - WATCHTOWER_NOTIFICATIONS=email
        # - WATCHTOWER_NOTIFICATION_EMAIL_FROM=REDACTED
        # - WATCHTOWER_NOTIFICATION_EMAIL_TO=REDACTED
        # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.mailgun.org
        # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
        # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=REDACTED
        # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=REDACTED
    labels:
        - "com.centurylinklabs.watchtower=true"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - proxy
